<?php

/*
 * The MIT License
 *
 * Copyright 2015 fabien.sanchez fzed51@gmail.com.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

require './src/TnsParser.php';
require './src/Exception/ParseException.php';

use fzed51\TnsParser\TnsParser;

$stringTnsName = "
# tnsnames.ora Network Configuration File: C:\\oracle\\Ora10\\network\\admin\\tnsnames.ora
# Generated by Oracle configuration tools.

MYSERVICE=
  (DESCRIPTION=
    (ADDRESS=
      (PROTOCOL=TCP)
      (HOST=localhost)
      (PORT=1521)
    )
    (CONNECT_DATA=
      (SERVICE_NAME=ORCL)
    )
  )

SERVEUR-TEST-WEB=
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = serveur1)(PORT = 1530))
      (ADDRESS = (PROTOCOL = TCP)(HOST = serveur2)(PORT = 1530))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = TEST_WEB)
    )
  )
";

$tns = TnsParser::parseString($stringTnsName);
print_r($tns);
